redis:
  sentinels:
    replicas: 3
    quorum: 2
    customConfig:
      - "down-after-milliseconds 2000"
      - "failover-timeout 3000"
  slaves:
    replicas: 3
    customConfig:
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "tcp-keepalive 60"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 1000000000 1000000000 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"

image:
  repository: joelws/redis-operator
  tag: 0.1.3
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
