apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "redis-operator.name" . }}
    chart: {{ include "redis-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}