apiVersion: operator.joelws.com/v1
kind: Redis
metadata:
  name: redis-default
  annotations:
   "helm.sh/hook": post-install
   "helm.sh/hook-weight": "-5"
spec:
  sentinels:
    replicas: {{ .Values.redis.sentinels.replicas }}
    quorum: {{ .Values.redis.sentinels.quorum }}
    customConfig:
      {{- range .Values.redis.sentinels.customConfig }}
      - {{ . }}
      {{- end}}
  slaves:
    replicas: {{ .Values.redis.slaves.replicas }}
    customConfig:
     {{- range .Values.redis.slaves.customConfig }}
     - {{ . }}
     {{- end}}